# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimplePlayerUsingPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimplePlayerUsingPods
  # Core video tracking functionality
  pod 'NewRelicVideoCore', :path => '../../../'
  
  # Tracker pods for specific player types
  pod 'NRAVPlayerTracker', :path => '../../../'
  pod 'NRIMATracker', :path => '../../../'
end
