# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'PiPExampleSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PiPExampleSwift
  pod 'NewRelicVideoCore', :path => '../../../'
  pod 'NRAVPlayerTracker', :path => '../../../'
  pod 'NRIMATracker', :path => '../../../'

  # Google IMA SDK for ad integration
  pod 'GoogleAds-IMA-iOS-SDK', '~> 3.18'
end
