# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimplePlayerWithAds' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimplePlayerWithAds
  # Pods for SimplePlayerUsingPods
  pod 'NewRelicVideoCore', :path => '../../../'
  pod 'NRAVPlayerTracker', :path => '../../../'
  pod 'NRIMATracker', :path => '../../../'
end
