platform :ios, '14.0'

target 'SimplePlayerWithAds' do
  use_frameworks!

  # Published pod — update this version to test a new release
  pod 'NewRelicVideoAgent', '4.1.2'
  pod 'NRAVPlayerTracker',  '4.1.2'
  pod 'NRIMATracker',       '4.1.2'
end
