# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimplePlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimplePlayer
  # Pods for SimplePlayerUsingPods
  pod 'NewRelicVideoAgent', :path => '../../../'
  pod 'NRAVPlayerTracker', :path => '../../../'
end
